services:
  - type: web
    name: parlay-state-search
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt gunicorn
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
